### ISSUE TITLE
安装报错了。。。

### ISSUE THREAD

**Issue by supermanzero** [yaoyao1987/vue-cli-multipage#3]
Error: connect ETIMEDOUT 173.194.72.128:80
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1081:14)
npm WARN vue-loader@8.5.2 requires a peer of babel-runtime@^6.0.0 but none was installed.
npm WARN oa-vue@0.1.0 No repository field.
npm WARN oa-vue@0.1.0 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.23.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.23.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/WRQ/Git/vue-cli-multipage/npm-debug.log

**Comment by yaoyao1987** [comment]
@supermanzero ，你的node版本是不是v6.4.0，我的node是v4.4.2，node版本的关系吧
